version: '3'

# Definindo serviços para orquestração com o Docker Compose
services:
  # Serviço Redis usando a imagem oficial do Redis
  redis-server:
    image: 'redis'
    
  # Serviço da aplicação Node.js
  node-app:
    build: .  # Utiliza o Dockerfile no diretório atual para construir a imagem
    ports:
      - "8080:8081"  # Mapeamento da porta do host para a porta do contêiner
