---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Adicionar usuário de app
      user:
        name: app
        comment: Usuário de aplicação
        uid: 500

    - name: Download do Maven
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz

    - name: Unzip do pacote Maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Instalação do Java
      yum:
        name: java-1.8.0-openjdk
        state: latest

    - name: Criação do diretório de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app

    # ... Outras tarefas ...

  roles:
    - configuracao-default-so

  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes
