Vagrant.configure("2") do |config|
  # Define a imagem base da VM
  config.vm.box = "centos/7"

  # Define o nome de host da máquina virtual
  config.vm.hostname = "control-node"

  # Configura uma rede privada com IP atribuído via DHCP
  config.vm.network "private_network", ip: "192.168.2.2", type: "dhcp"

  # Configura uma pasta sincronizada usando NFS com opções específicas
  config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["vers=3,tcp"]

  # Executa um script de provisionamento
  config.vm.provision "shell", path: "provision.sh"

  # Desativa a atualização automática do VirtualBox Guest Additions
  config.vbguest.auto_update = false
end
