
Vagrant.configure("2") do |config|  
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.2.2", type: "dhcp"  
  config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["vers=3,tcp"]  
  config.vm.provision "shell", path: "provision.sh"  
  config.vbguest.auto_update = false
  
end
