Vagrant.configure("2") do |config|
  # Define a imagem base da VM
  config.vm.box = "centos/7"

  # Define o nome da máquina virtual
  config.vm.hostname = "app01"

  # Configura uma rede privada com IP estático
  config.vm.network "private_network", ip: "192.168.2.3"

  # Desabilita a atualização automática do VirtualBox Guest Additions
  config.vbguest.auto_update = false

  # Configura uma porta encaminhada (forwarded port)
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Executa um script de provisionamento
  config.vm.provision "shell", path: "provision.sh"
end
