# Define a versão da configuração do Vagrant
Vagrant.configure("2") do |config|

    # Executa um comando shell inline para imprimir uma mensagem
    config.vm.provision "shell", inline: "echo Config docker swarm cluster"

    # Define um nó "manager" da sua configuração
    config.vm.define "manager" do |manager|
        manager.vm.box = "centos/7"  # Escolhe a imagem base CentOS 7 para o nó "manager"
        manager.vm.hostname = "manager"  # Define o nome de host do nó como "manager"
        manager.vm.provision "shell", path: "provision.sh"  # Executa um script de provisionamento
        manager.vm.network "private_network", ip: "192.168.2.2"  # Configura uma rede privada com IP específico
        manager.vm.network "forwarded_port", guest: 80, host: 8090  # Mapeia uma porta do host para o nó "manager"
        config.vbguest.auto_update = false  # Desativa as atualizações automáticas do VirtualBox Guest Additions
    end

    # Define um nó "worker1" da sua configuração
    config.vm.define "worker1" do |worker1|
        worker1.vm.box = "centos/7"  # Escolhe a imagem base CentOS 7 para o nó "worker1"
        worker1.vm.hostname = "worker1"  # Define o nome de host do nó como "worker1"
        worker1.vm.provision "shell", path: "provision.sh"  # Executa um script de provisionamento
        worker1.vm.network "private_network", ip: "192.168.2.3"  # Configura uma rede privada com IP específico
        config.vbguest.auto_update = false  # Desativa as atualizações automáticas do VirtualBox Guest Additions
    end

    # Define um nó "worker2" da sua configuração
    config.vm.define "worker2" do |worker2|
        worker2.vm.box = "centos/7"  # Escolhe a imagem base CentOS 7 para o nó "worker2"
        worker2.vm.hostname = "worker2"  # Define o nome de host do nó como "worker2"
        worker2.vm.provision "shell", path: "provision.sh"  # Executa um script de provisionamento
        worker2.vm.network "private_network", ip: "192.168.2.4"  # Configura uma rede privada com IP específico
        config.vbguest.auto_update = false  # Desativa as atualizações automáticas do VirtualBox Guest Additions
    end
end
