Vagrant.configure("2") do |config|
  # Define a imagem base da VM
  config.vm.box = "centos/7"

  # Configura o redirecionamento de portas (forwarded ports)
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Executa um script de provisionamento
  config.vm.provision "shell", path: "provision.sh"

  # Desabilita a atualização automática do VirtualBox Guest Additions
  config.vbguest.auto_update = false
end
