Vagrant.configure("2") do |config|
  # Define a imagem base da VM
  config.vm.box = "centos/7"

  # Define o nome de host da máquina virtual
  config.vm.hostname = "db01"

  # Configura uma rede privada com um IP estático
  config.vm.network "private_network", ip: "192.168.2.4"

  # Desativa a atualização automática do VirtualBox Guest Additions
  config.vbguest.auto_update = false

  # Configura uma porta encaminhada (forwarded port) para o MySQL
  config.vm.network "forwarded_port", guest: 3306, host: 3307

  # Executa um script de provisionamento
  config.vm.provision "shell", path: "provision.sh"
end
